# -*- coding: utf-8 -*-
"""courbe_monotone_de_puissance_et_nouvelle_valeur_souscrite.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j2tTcqjUtaoP42tiJyZD4rz6OG-tu6E_
"""

import pandas as pd
import seaborn as sns

data = pd.read_csv('/content/ACDC_CC_STM A 25_11_2022.csv')
data.head()

data = data.groupby('date').mean()
data.head()

import matplotlib.pyplot as plt
n, bins, patches = plt.hist(data['consomation'],  cumulative=-1,orientation='horizontal',fill=False)

bins

n = np.array(list(n)+ [0])

plt.plot(n,bins)
#plt.savefig('photo.jpg')

def nouvel_valeur_souscrite(df_in, col_name,seuil_hyper):
    q1 = df_in[col_name].quantile(0.25)
    q3 = df_in[col_name].quantile(0.75)
    iqr = q3-q1 #Interquartile range
    
    seuil = q3+seuil_hyper*iqr

    return seuil

valeur_max = nouvel_valeur_souscrite(data,'consomation',1.0)

valeur_max

plt.close()